services:
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  db_data:
  redis_data: