services:
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379

  validator:
    image: daturaai/compute-subnet-validator:latest
    env_file: ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    expose:
      - ${INTERNAL_PORT}
    volumes:
      - ${HOST_WALLET_DIR}:/root/.bittensor/wallets
    depends_on:
      - db
      - redis

  connector:
    image: daturaai/compute-subnet-validator:latest
    env_file: ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python src/connector.py
    volumes:
      - ${HOST_WALLET_DIR}:/root/.bittensor/wallets
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data: